export const menu = [
  {
    restaurant_id: 1,
    menu: [
      {
        id: 1,
        name: "Spaghetti Carbonara",
        description: "Classic Italian Pasta with creamy sauce.",
        price: 12.99,
        category: "Pasta",
        image: "../assets/images/dishes/spaghetti_carbonara.jpg",
      },
      {
        id: 2,
        name: "Margherita Pizza",
        description: "Traditional pizza with fresh mozzarella and basil.",
        price: 10.99,
        category: "Pizzas",
        image: "../assets/images/dishes/margherita_pizza.jpg",
      },
      {
        id: 3,
        name: "Lasagna",
        description: "Layered Pasta with rich meat sauce and cheese.",
        price: 14.99,
        category: "Salads",
        image: "../assets/images/dishes/lasagna.jpg",
      },
      {
        id: 4,
        name: "Pepperoni Pizza",
        description: "Classic pizza topped with pepperoni slices.",
        price: 12.99,
        category: "Pizzas",
        offers: "Buy One Get One Free",
        image: "../assets/images/dishes/pepperoni_pizza.jpg",
      },
    ],
  },
  {
    restaurant_id: 2,
    menu: [
      {
        id: 1,
        name: "Salmon Nigiri",
        description: "Fresh salmon on top of seasoned rice.",
        price: 8.99,
        category: "Sushi",
        image: "../assets/images/dishes/salmon_nigiri.jpg",
      },
      {
        id: 2,
        name: "Tempura Udon",
        description: "Thick udon noodles in a savory broth with tempura.",
        price: 11.99,
        category: "Pasta",
        image: "../assets/images/dishes/tempura_udon.jpg",
      },
      {
        id: 3,
        name: "California Roll",
        description: "Sushi roll with crab, avocado, and cucumber.",
        price: 9.49,
        category: "Sushi",
        image: "../assets/images/dishes/california_roll.jpg",
      },
      {
        id: 4,
        name: "Chocolate Cake",
        description: "Rich and moist chocolate cake.",
        price: 6.99,
        category: "Cakes",
        offers: "Free Delivery",
        image: "../assets/images/dishes/chocolate_cake.jpg",
      },
    ],
  },
  {
    restaurant_id: 3,
    menu: [
      {
        id: 1,
        name: "CheeseBurgers",
        description: "Juicy beef patty with cheddar cheese.",
        price: 9.99,
        category: "Burgers",
        image: "../assets/images/dishes/cheeseBurgers.jpg",
      },
      {
        id: 2,
        name: "Chicken Wings",
        description: "Crispy chicken wings with a spicy sauce.",
        price: 7.99,
        category: "meat",
        image: "../assets/images/dishes/chicken_wings.jpg",
      },
      {
        id: 3,
        name: "Onion Rings",
        description: "Crispy onion rings served with dipping sauce.",
        price: 5.99,
        category: "Sushi",
        image: "../assets/images/dishes/onion_rings.jpg",
      },
      {
        id: 4,
        name: "Caesar Salad",
        description: "Fresh salad with Caesar dressing and croutons.",
        price: 7.99,
        category: "Salads",
        offers: "None",
        image: "../assets/images/dishes/caesar_salad.jpg",
      },
    ],
  },
  {
    restaurant_id: 4,
    menu: [
      {
        id: 1,
        name: "Chicken Curry",
        description: "Spicy chicken curry with a rich, creamy sauce.",
        price: 13.99,
        category: "Sushi",
        image: "../assets/images/dishes/chicken_curry.jpg",
      },
      {
        id: 2,
        name: "Paneer Tikka",
        description: "Grilled paneer cubes marinated in spices.",
        price: 11.99,
        category: "meat",
        image: "../assets/images/dishes/paneer_tikka.jpg",
      },
      {
        id: 3,
        name: "Naan Bread",
        description: "Soft, fluffy bread baked in a tandoor oven.",
        price: 2.99,
        category: "Burgers",
        image: "../assets/images/dishes/naan_bread.jpg",
      },
      {
        id: 4,
        name: "Margherita Pizza",
        description: "Traditional pizza with fresh mozzarella and basil.",
        price: 10.99,
        category: "Pizzas",
        offers: "Discounts",
        image: "../assets/images/dishes/margherita_pizza.jpg",
      },
    ],
  },
  {
    restaurant_id: 5,
    menu: [
      {
        id: 1,
        name: "Beef Tacos",
        description: "Soft tortillas filled with seasoned beef and toppings.",
        price: 9.49,
        category: "meat",
        image: "../assets/images/dishes/beef_tacos.jpg",
      },
      {
        id: 2,
        name: "Chicken Enchiladas",
        description:
          "Rolled tortillas filled with chicken and smothered in sauce.",
        price: 12.99,
        category: "meat",
        image: "../assets/images/dishes/chicken_enchiladas.jpg",
      },
      {
        id: 3,
        name: "Guacamole and Chips",
        description: "Fresh guacamole served with crispy tortilla chips.",
        price: 6.99,
        category: "Pasta",
        image: "../assets/images/dishes/guacamole_chips.jpg",
      },
    ],
  },
];
